# Generated by Django 3.1.1 on 2020-09-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='src',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
